service: jpfruit
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128
  timeout: 15
  stage: dev2
  region: ap-south-1

functions:
  api:
    handler: lambda.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /
